import os
from glob import glob

from setuptools import setup

package_name = 'jetnano_bringup'

setup(
    name=package_name,
    version='0.1.0',
    packages=['jetnano_bringup'],
    data_files=[
        ('share/ament_index/resource_index/packages', ['resource/' + package_name]),
        (os.path.join('share', package_name), ['package.xml']),
        (os.path.join('share', package_name, 'launch'), glob('launch/*.launch.py')),
        (os.path.join('share', package_name, 'config'), glob('config/*.yaml')),
        (os.path.join('lib', package_name), ['scripts/cuvslam_vo.sh', 'scripts/wifi_watchdog.sh',
                                             'scripts/drive_record.sh', 'scripts/save_3d_map.sh',
                                             'scripts/nav2_ctl.sh', 'scripts/predrive.sh']),
    ],
    install_requires=['setuptools'],
    zip_safe=True,
    maintainer='stevej52',
    maintainer_email='stevej52@gmail.com',
    description='Bringup launch files for the jetnano robot',
    license='Apache-2.0',
    tests_require=['pytest'],
    entry_points={
        'console_scripts': [
            'fake_sensors = jetnano_bringup.fake_sensors:main',
            'tilt_guard = jetnano_bringup.tilt_guard:main',
            'grid_to_points = jetnano_bringup.grid_to_points:main',
            'bno055_lean = jetnano_bringup.bno055_lean:main',
            'imu_base_relay = jetnano_bringup.imu_base_relay:main',
            'vo_watchdog = jetnano_bringup.vo_watchdog:main',
            'lidar_odom_relay = jetnano_bringup.lidar_odom_relay:main',
            'drive_report = jetnano_bringup.drive_report:main',
            'drive_log = jetnano_bringup.drive_log:main',
            'battery_monitor = jetnano_bringup.battery_monitor:main',
            'cliff_guard = jetnano_bringup.cliff_guard:main',
            'make_voice = jetnano_bringup.voice:main',
            'sounds = jetnano_bringup.sounds:main',
            'quiet = jetnano_bringup.quiet:main',
            'motion_watch = jetnano_bringup.motion_watch:main',
            'ears = jetnano_bringup.ears:main',
            'xvf_tune = jetnano_bringup.xvf:main',
            'people = jetnano_bringup.people:main',
            'rail_check = jetnano_bringup.rail_check:main',
            'predrive = jetnano_bringup.predrive:main',
            'guard_flow = jetnano_bringup.guard_flow:main',
            'voice = jetnano_bringup.voice_switch:main',
            'housekeeping = jetnano_bringup.housekeeping:main',
            'settle = jetnano_bringup.settle:main',
            'motion_check = jetnano_bringup.motion_check:main',
            'csi_cameras = jetnano_bringup.csi_cameras:main',
            'listen = jetnano_bringup.listen:main',
            'speak = jetnano_bringup.speak:main',
            'brain = jetnano_bringup.brain:main',
            'watchdog = jetnano_bringup.watchdog:main',
            'throttle_calibration = jetnano_bringup.throttle_calibration:main',
            'rates = jetnano_bringup.rates:main',
            'voices = jetnano_bringup.speaker:main',
        ],
    },
)
